name: Build OpenWrt

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
        file wget ccache

    - name: Clone OpenWrt source code
      run: |
        git clone --depth 1 https://github.com/openwrt/openwrt.git

    - name: Set up Git user
      run: |
        git config --global user.email "52329982+Lyceris-chan@users.noreply.github.com"
        git config --global user.name "Lyceris-chan"

    - name: Add support for Mercusys MR70X
      run: |
        cd openwrt
        git fetch https://github.com/nicefile/openwrt-vector mr70x
        git cherry-pick 04b9b13a8de5116a97d79a2f5b18163f799f10aa

    - name: Update feeds and install all available feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Prepare OpenWrt configuration
      run: |
        cd openwrt
        cp -f ../.config .config

    - name: Setup CCache
      uses: stupidloud/cachewrtbuild@main
      with:
        ccache: 'true'
        prefix: openwrt

    - name: Build OpenWrt firmware
      run: |
        cd openwrt
        make -j "$(nproc)"

    - name: Upload firmware
      uses: actions/upload-artifact@v2
      with:
        name: openwrt-firmware
        path: openwrt/bin/targets/ramips/mt7621/openwrt-ramips-mt7621-mercusys_mr70x*
