name: Build OpenWrt for ASUS RT-AX53U

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
        file wget ccache

    - name: Clone OpenWrt Source Code
      run: |
        git clone --depth 1 --branch v23.05.3 https://github.com/openwrt/openwrt.git

    - name: Update and Install OpenWrt Feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Prepare OpenWrt Configuration
      run: |
        cd openwrt
        cp -f ../.config .config

    - name: Setup cachewrtbuild
      uses: stupidloud/cachewrtbuild@main
      with:
        ccache: 'true'
        prefix: ${{ github.workspace }}/openwrt

    - name: Build OpenWrt Firmware
      run: |
        cd openwrt
        make -j "$(nproc)"


    - name: Automatic Release
      uses: maggie0002/actions/packages/automatic-releases@built-packages
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "RT-AX53U"
        prerelease: false
        title: "Development Build"
        files: |
          openwrt/bin/targets/ramips/mt7621/openwrt-23.05.3-ramips-mt7621-asus_rt-ax53u-initramfs-kernel.bin
          openwrt/bin/targets/ramips/mt7621/openwrt-23.05.3-ramips-mt7621-asus_rt-ax53u-squashfs-factory.bin
          openwrt/bin/targets/ramips/mt7621/openwrt-23.05.3-ramips-mt7621-asus_rt-ax53u-squashfs-sysupgrade.bin
          openwrt/bin/targets/ramips/mt7621/openwrt-23.05.3-ramips-mt7621-asus_rt-ax53u.manifest

